### ISSUE TITLE
WebServer must be stopped

### ISSUE THREAD

**Issue by sebastienserre** [kikinovak/letsencrypt#1]
Hello,
I tested your script but a step is mmissing, the http-01 failed if webser is running as certbot can't use the port 80.
I succeed to renew with a `sudo service apache2 stop` but I can't add it in a cron. 

Is it possible to add a step to stop apache and restart it right after ?

**Comment by sebastienserre** [comment]
Sorry, I changed the line 16 from "httpd" to "apache2" on Ubuntu Server and it's OK ;-)
Thanks for this script

**Comment by kikinovak** [comment]
Hi Sébastien,

Sorry I only saw your message now. I'm not very familiar with Github messages. It seems like my repos have gained some popularity lately.

Cheers,

Niki
